// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQDxIq6Rb4u8kdApduQr0HOeBs4z5UNj0',
    appId: '1:485174540934:web:901df0ce77bde62f702f07',
    messagingSenderId: '485174540934',
    projectId: 'c-prototype-a69d0',
    authDomain: 'c-prototype-a69d0.firebaseapp.com',
    storageBucket: 'c-prototype-a69d0.appspot.com',
    measurementId: 'G-FH8W0Z8E98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzfPpns2Ik5U4GpyvBvjIIiLMAli7OsXk',
    appId: '1:485174540934:android:dfbbd3ef0a658788702f07',
    messagingSenderId: '485174540934',
    projectId: 'c-prototype-a69d0',
    storageBucket: 'c-prototype-a69d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAx-0zCVLpd_hpIAuR6CQxBmeJGYEgOKo',
    appId: '1:485174540934:ios:2f72db34b4bf3106702f07',
    messagingSenderId: '485174540934',
    projectId: 'c-prototype-a69d0',
    storageBucket: 'c-prototype-a69d0.appspot.com',
    iosClientId: '485174540934-n95u0vdrqs40u76cheni24lm2kebgqd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.cProto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAx-0zCVLpd_hpIAuR6CQxBmeJGYEgOKo',
    appId: '1:485174540934:ios:2f72db34b4bf3106702f07',
    messagingSenderId: '485174540934',
    projectId: 'c-prototype-a69d0',
    storageBucket: 'c-prototype-a69d0.appspot.com',
    iosClientId: '485174540934-n95u0vdrqs40u76cheni24lm2kebgqd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.cProto',
  );
}
